version: 2
jobs:
  get-dependencies:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ checksum "package-lock.json" }}-{{ arch }}
      - run: 
          name: Installing dependencies
          command: npm install
      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}-{{ arch }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ checksum "package-lock.json" }}-{{ arch }}
      - run: 
          name: Checking code syntax
          command: npm run lint
      - run:
          name: Running unit tests
          command: npm run test
  build:
    docker: 
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ checksum "package-lock.json" }}-{{ arch }}
      - run:
          name: build
          command: npm run build
      - persist_to_workspace:
          root: build
          paths:
            - .
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: npm-{{ checksum "package-lock.json" }}-{{ arch }}
      - attach_workspace:
          at: build
      - deploy:
          name: Deploying to Firebase
          command: npx firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
workflows:
  version: 2
  build:
    jobs:
      - get-dependencies
      - test:
          requires:
            - get-dependencies
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
    