version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install
      - run:
        name: unit tests
        command: yarn run test
      - run:
        name: lint check
        command: yarn run lint
      - run:
        name: build
        command: yarn run build
workflows:
  version: 2
  build:
    jobs:
      - build
    