version: 2
jobs:
  get-dependencies:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: yarn-v2-{{ checksum "yarn.lock" }}-{{ arch }}
      - run: 
          name: Installing dependencies
          command: yarn install
      - save_cache:
          key: yarn-v2-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
            - node_modules
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: yarn-v2-{{ checksum "yarn.lock" }}-{{ arch }}
      - run: 
          name: Checking code syntax
          command: yarn run lint
      - run:
          name: Running unit tests
          command: yarn run test
  build:
    docker: 
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: yarn-v2-{{ checksum "yarn.lock" }}-{{ arch }}
      - run:
          name: build
          command: yarn run build
      - persist_to_workspace:
          root: .
          paths:
            - build
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - deploy:
          name: Deploying to Firebase
          command: yarn firebase deploy --token "$FIREBASE_TOKEN" --non-interactive
workflows:
  version: 2
  build:
    jobs:
      - get-dependencies
      - test:
          requires:
            - get-dependencies
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
    